FROM node:22-slim AS builder

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install

ARG NEXT_PUBLIC_API_HOST
ENV NEXT_PUBLIC_API_HOST=$NEXT_PUBLIC_API_HOST

COPY . .

EXPOSE 3000
CMD ["npm", "run", "dev"]