[pytest]
addopts = -ra -vv

testpaths = app/modules tests

filterwarnings =
    ignore:Accessing argon2.__version__ is deprecated.*:DeprecationWarning:passlib.handlers.argon2

python_files = test_*.py test.py *_test.py
python_classes = Test*
python_functions = test_*
