"""auto_migration

Revision ID: 2675b6f36218
Revises: f9ec8a6df4f7
Create Date: 2026-07-28 16:22:44.006649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2675b6f36218'
down_revision: Union[str, Sequence[str], None] = 'f9ec8a6df4f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userkey',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key_blob', sa.LargeBinary(), nullable=False),
    sa.Column('kek_version', sa.Integer(), nullable=False),
    sa.Column('hash_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_userkey_id'), 'userkey', ['id'], unique=True)
    op.create_index(op.f('ix_userkey_kek_version'), 'userkey', ['kek_version'], unique=False)
    op.add_column('note', sa.Column('password', sa.String(), nullable=True))
    op.add_column('note', sa.Column('is_encrypted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'is_encrypted')
    op.drop_column('note', 'password')
    op.drop_index(op.f('ix_userkey_kek_version'), table_name='userkey')
    op.drop_index(op.f('ix_userkey_id'), table_name='userkey')
    op.drop_table('userkey')
    # ### end Alembic commands ###
