"""add note ydoc

Revision ID: 3a5eadebb682
Revises: dcf18706f7b9
Create Date: 2026-09-30 03:37:18.184866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a5eadebb682'
down_revision: Union[str, Sequence[str], None] = 'dcf18706f7b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('ydoc', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'ydoc')
    # ### end Alembic commands ###
