"""auto_migration

Revision ID: 3f3aae4720e5
Revises: 6e952fab87eb
Create Date: 2025-12-23 00:18:39.085737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f3aae4720e5'
down_revision: Union[str, Sequence[str], None] = '6e952fab87eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'is_deleted')
    # ### end Alembic commands ###
