"""auto_migration

Revision ID: 431531c0f64b
Revises: f43bb149d1cf
Create Date: 2026-07-16 05:07:26.790581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '431531c0f64b'
down_revision: Union[str, Sequence[str], None] = 'f43bb149d1cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace_member', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace_member', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
