"""auto_migration

Revision ID: 4a422e0a8e04
Revises: 151b9f2f9c99
Create Date: 2026-07-06 08:44:06.356479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a422e0a8e04'
down_revision: Union[str, Sequence[str], None] = '641e34762ba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('notesnapshot_note_id_fkey'), 'notesnapshot', type_='foreignkey')
    op.create_foreign_key(None, 'notesnapshot', 'note', ['note_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notesnapshot', type_='foreignkey')
    op.create_foreign_key(op.f('notesnapshot_note_id_fkey'), 'notesnapshot', 'note', ['note_id'], ['id'])
    # ### end Alembic commands ###
