"""auto_migration

Revision ID: 4d74eb175ec0
Revises: 3087dbdf34d9
Create Date: 2026-07-15 06:36:35.262413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d74eb175ec0'
down_revision: Union[str, Sequence[str], None] = '3087dbdf34d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'note', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.drop_column('note', 'workspace_id')
    # ### end Alembic commands ###
