"""auto_migration

Revision ID: 540a075a04f8
Revises: 4a422e0a8e04
Create Date: 2026-07-07 01:12:30.019312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '540a075a04f8'
down_revision: Union[str, Sequence[str], None] = '4a422e0a8e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('note', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('note', 'deleted_at')
    # ### end Alembic commands ###
