"""add note_link

Revision ID: 55d0db0f33f9
Revises: 5b1df84155cb
Create Date: 2026-09-29 00:27:10.629245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55d0db0f33f9'
down_revision: Union[str, Sequence[str], None] = '5b1df84155cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_link',
    sa.Column('source_note_id', sa.Integer(), nullable=False),
    sa.Column('target_note_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_note_id'], ['note.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_note_id'], ['note.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_note_id', 'target_note_id')
    )
    op.create_index(op.f('ix_note_link_target_note_id'), 'note_link', ['target_note_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_link_target_note_id'), table_name='note_link')
    op.drop_table('note_link')
    # ### end Alembic commands ###
