"""add folder

Revision ID: 5b1df84155cb
Revises: 2675b6f36218
Create Date: 2026-09-22 06:29:57.108139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b1df84155cb'
down_revision: Union[str, Sequence[str], None] = '2675b6f36218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('hash_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['folder.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_id')
    )
    op.create_index(op.f('ix_folder_id'), 'folder', ['id'], unique=True)
    op.create_index(op.f('ix_folder_parent_id'), 'folder', ['parent_id'], unique=False)
    op.create_index(op.f('ix_folder_user_id'), 'folder', ['user_id'], unique=False)
    op.add_column('note', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_note_folder_id'), 'note', ['folder_id'], unique=False)
    op.create_foreign_key('fk_note_folder_id', 'note', 'folder', ['folder_id'], ['id'],
                          ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_note_folder_id', 'note', type_='foreignkey')
    op.drop_index(op.f('ix_note_folder_id'), table_name='note')
    op.drop_column('note', 'folder_id')
    op.drop_index(op.f('ix_folder_user_id'), table_name='folder')
    op.drop_index(op.f('ix_folder_parent_id'), table_name='folder')
    op.drop_index(op.f('ix_folder_id'), table_name='folder')
    op.drop_table('folder')
    # ### end Alembic commands ###
