"""auto_migration

Revision ID: 6e952fab87eb
Revises: b4a8238954a5
Create Date: 2025-12-22 19:39:20.208455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e952fab87eb'
down_revision: Union[str, Sequence[str], None] = 'b4a8238954a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('is_protected', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'is_protected')
    # ### end Alembic commands ###
