"""auto_migration

Revision ID: ab67ff6a6382
Revises: 32bcf111e105
Create Date: 2026-07-14 02:09:06.609425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab67ff6a6382'
down_revision: Union[str, Sequence[str], None] = '32bcf111e105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_approval', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_approval')
    op.drop_column('user', 'is_superuser')
    # ### end Alembic commands ###
