"""auto_migration

Revision ID: acc5f6aeae79
Revises: ab67ff6a6382
Create Date: 2026-07-14 12:25:56.618681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acc5f6aeae79'
down_revision: Union[str, Sequence[str], None] = 'ab67ff6a6382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('note_user_id_fkey'), 'note', type_='foreignkey')
    op.create_foreign_key(None, 'note', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('template_user_id_fkey'), 'template', type_='foreignkey')
    op.create_foreign_key(None, 'template', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'template', type_='foreignkey')
    op.create_foreign_key(op.f('template_user_id_fkey'), 'template', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.create_foreign_key(op.f('note_user_id_fkey'), 'note', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
