"""auto_migration

Revision ID: dbaaac0acecf
Revises: 4c9f8c08771a
Create Date: 2026-07-05 19:24:32.244907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbaaac0acecf'
down_revision: Union[str, Sequence[str], None] = '4c9f8c08771a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notesnapshot', sa.Column('name', sa.String(), nullable=True))
    op.add_column('notesnapshot', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notesnapshot', 'description')
    op.drop_column('notesnapshot', 'name')
    # ### end Alembic commands ###
