"""add api_token

Revision ID: dcf18706f7b9
Revises: 2c92a9280246
Create Date: 2026-09-30 00:59:15.749885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcf18706f7b9'
down_revision: Union[str, Sequence[str], None] = '2c92a9280246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apitoken',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hash_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_id')
    )
    op.create_index(op.f('ix_apitoken_id'), 'apitoken', ['id'], unique=True)
    op.create_index(op.f('ix_apitoken_token_hash'), 'apitoken', ['token_hash'], unique=True)
    op.create_index(op.f('ix_apitoken_user_id'), 'apitoken', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apitoken_user_id'), table_name='apitoken')
    op.drop_index(op.f('ix_apitoken_token_hash'), table_name='apitoken')
    op.drop_index(op.f('ix_apitoken_id'), table_name='apitoken')
    op.drop_table('apitoken')
    # ### end Alembic commands ###
