"""auto_migration

Revision ID: f43bb149d1cf
Revises: 4d74eb175ec0
Create Date: 2026-07-15 06:42:54.903496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f43bb149d1cf'
down_revision: Union[str, Sequence[str], None] = '4d74eb175ec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_note',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('note_id', 'workspace_id')
    )
    op.drop_constraint(op.f('note_workspace_id_fkey'), 'note', type_='foreignkey')
    op.drop_column('note', 'workspace_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('workspace_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('note_workspace_id_fkey'), 'note', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_table('workspace_note')
    # ### end Alembic commands ###
