"""add_preference

Revision ID: f9ec8a6df4f7
Revises: 431531c0f64b
Create Date: 2026-07-16 05:25:19.080080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9ec8a6df4f7'
down_revision: Union[str, Sequence[str], None] = '431531c0f64b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preference',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trash_policy', sa.String(), nullable=False),
    sa.Column('snapshot_policy', sa.String(), nullable=False),
    sa.Column('hash_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_preference_id'), 'preference', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preference_id'), table_name='preference')
    op.drop_table('preference')
    # ### end Alembic commands ###
